# Generated by Django 5.0.6 on 2024-07-03 05:03

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kadai', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Medicine',
            fields=[
                ('medicineid', models.CharField(max_length=8, primary_key=True, serialize=False, verbose_name='薬剤ID')),
                ('medicinename', models.CharField(max_length=64, verbose_name='薬剤名')),
                ('unit', models.CharField(max_length=8, verbose_name='単位')),
            ],
        ),
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('patid', models.CharField(max_length=8, primary_key=True, serialize=False, verbose_name='患者ID')),
                ('patfname', models.CharField(max_length=64, verbose_name='患者名')),
                ('patlname', models.CharField(max_length=64, verbose_name='患者姓')),
                ('hokenmei', models.CharField(max_length=64, verbose_name='保険証記号番号')),
                ('hokenexp', models.DateField(verbose_name='有効期限')),
            ],
        ),
        migrations.CreateModel(
            name='Shiiregyosha',
            fields=[
                ('shiireid', models.CharField(max_length=8, primary_key=True, serialize=False, verbose_name='仕入れ先ID')),
                ('shiiremei', models.CharField(max_length=64, verbose_name='仕入れ先名')),
                ('shiireaddress', models.CharField(max_length=64, verbose_name='仕入れ先住所')),
                ('shiiretel', models.CharField(max_length=13, verbose_name='仕入れ先電話番号')),
                ('shihonkin', models.IntegerField(verbose_name='資本金')),
                ('nouki', models.IntegerField(verbose_name='納期')),
            ],
        ),
        migrations.CreateModel(
            name='Tabyouin',
            fields=[
                ('tabyouinid', models.CharField(max_length=8, primary_key=True, serialize=False, verbose_name='他病院ID')),
                ('tabyouinmei', models.CharField(max_length=64, verbose_name='他病院名')),
                ('tabyouinaddress', models.CharField(max_length=64, verbose_name='他病院住所')),
                ('tabyouintel', models.CharField(max_length=13, verbose_name='他病院電話番号')),
                ('tabyouinshihonkin', models.IntegerField(verbose_name='資本金')),
                ('kyukyu', models.IntegerField(verbose_name='救急フラグ')),
            ],
        ),
        migrations.CreateModel(
            name='Treatment',
            fields=[
                ('treatmentid', models.CharField(default=uuid.uuid4, max_length=8, primary_key=True, serialize=False)),
                ('quantity', models.IntegerField()),
                ('treatmentdata', models.TextField()),
                ('medicine', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kadai.medicine')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kadai.patient')),
            ],
        ),
    ]
